---

- name: requirements > Sudo package check
  command: "{{ sudo_requirement_check }}"
  check_mode: false
  failed_when: false
  changed_when: false
  register: _elao_sudo_package_check_output

- name: requirements > Sudo package check fail
  fail:
    msg: Package "sudo" must be installed
  when: _elao_sudo_package_check_output.rc != 0
