---

- name: Ubuntu | add ppa repo
  apt_repository:
    repo: "{{ pamsshagentauth_ppa_repo }}"
    state: present
  when: ansible_distribution == 'Ubuntu'
  register: repo
  notify:
    - update apt cache

- meta: flush_handlers
  when: repo.changed
